<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            [
                'module' => 'Dashboard',
                'name' => 'Dashboard View',
                'route' => 'admin.dashboard',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Users',
                'name' => 'Users View',
                'route' => 'admin.users.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Users',
                'name' => 'Users Create',
                'route' => 'admin.users.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Users',
                'name' => 'Users Edit',
                'route' => 'admin.users.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Users',
                'name' => 'Users Delete',
                'route' => 'admin.users.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Roles',
                'name' => 'Roles View',
                'route' => 'admin.roles.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Roles',
                'name' => 'Roles Create',
                'route' => 'admin.roles.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Roles',
                'name' => 'Roles Edit',
                'route' => 'admin.roles.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Roles',
                'name' => 'Roles Delete',
                'route' => 'admin.roles.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Permissions',
                'name' => 'Permissions View',
                'route' => 'admin.permissions.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Permissions',
                'name' => 'Permissions Create',
                'route' => 'admin.permissions.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Permissions',
                'name' => 'Permissions Edit',
                'route' => 'admin.permissions.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Permissions',
                'name' => 'Permissions Delete',
                'route' => 'admin.permissions.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Leads',
                'name' => 'Leads View',
                'route' => 'admin.leads.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Leads',
                'name' => 'Leads Create',
                'route' => 'admin.leads.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Leads',
                'name' => 'Leads Edit',
                'route' => 'admin.leads.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Leads',
                'name' => 'Leads Delete',
                'route' => 'admin.leads.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Clients',
                'name' => 'Clients View',
                'route' => 'admin.clients.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Clients',
                'name' => 'Clients Create',
                'route' => 'admin.clients.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Clients',
                'name' => 'Clients Edit',
                'route' => 'admin.clients.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Clients',
                'name' => 'Clients Delete',
                'route' => 'admin.clients.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Follow Ups',
                'name' => 'Follow Ups View',
                'route' => 'admin.followups.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Follow Ups',
                'name' => 'Follow Ups Create',
                'route' => 'admin.followups.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Follow Ups',
                'name' => 'Follow Ups Edit',
                'route' => 'admin.followups.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Follow Ups',
                'name' => 'Follow Ups Delete',
                'route' => 'admin.followups.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Projects',
                'name' => 'Projects View',
                'route' => 'admin.projects.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Projects',
                'name' => 'Projects Create',
                'route' => 'admin.projects.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Projects',
                'name' => 'Projects Edit',
                'route' => 'admin.projects.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Projects',
                'name' => 'Projects Delete',
                'route' => 'admin.projects.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Quotations',
                'name' => 'Quotations View',
                'route' => 'admin.quotations.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Quotations',
                'name' => 'Quotations Create',
                'route' => 'admin.quotations.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Quotations',
                'name' => 'Quotations Edit',
                'route' => 'admin.quotations.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Quotations',
                'name' => 'Quotations Delete',
                'route' => 'admin.quotations.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Invoices',
                'name' => 'Invoices View',
                'route' => 'admin.invoices.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Invoices',
                'name' => 'Invoices Create',
                'route' => 'admin.invoices.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Invoices',
                'name' => 'Invoices Edit',
                'route' => 'admin.invoices.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Invoices',
                'name' => 'Invoices Delete',
                'route' => 'admin.invoices.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Payments',
                'name' => 'Payments View',
                'route' => 'admin.payments.index',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Payments',
                'name' => 'Payments Create',
                'route' => 'admin.payments.create',
                'action' => 'create',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Payments',
                'name' => 'Payments Edit',
                'route' => 'admin.payments.edit',
                'action' => 'edit',
                'position' => 3,
                'status' => true,
            ],
            [
                'module' => 'Payments',
                'name' => 'Payments Delete',
                'route' => 'admin.payments.destroy',
                'action' => 'delete',
                'position' => 4,
                'status' => true,
            ],
            [
                'module' => 'Lead Reports',
                'name' => 'Lead Reports View',
                'route' => 'admin.reports.leads',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Sales Reports',
                'name' => 'Sales Reports View',
                'route' => 'admin.reports.sales',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'User Reports',
                'name' => 'User Reports View',
                'route' => 'admin.reports.users',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Company Settings',
                'name' => 'Company Settings View',
                'route' => 'admin.settings.company',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Company Settings',
                'name' => 'Company Settings Edit',
                'route' => 'admin.settings.company.update',
                'action' => 'edit',
                'position' => 2,
                'status' => true,
            ],
            [
                'module' => 'Profile',
                'name' => 'Profile View',
                'route' => 'admin.profile',
                'action' => 'view',
                'position' => 1,
                'status' => true,
            ],
            [
                'module' => 'Profile',
                'name' => 'Profile Edit',
                'route' => 'admin.profile.update',
                'action' => 'edit',
                'position' => 2,
                'status' => true,
            ],
        ];

        Permission::where('name', 'like', '%.%')->delete();

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                [
                    'name' => $permission['name'],
                    'guard_name' => 'web',
                ],
                [
                    'module' => $permission['module'],
                    'route' => $permission['route'],
                    'action' => $permission['action'],
                    'position' => $permission['position'],
                    'status' => $permission['status'],
                ]
            );
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}